spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0

    # Redis服务器地址
    host: 192.168.137.241

    # Redis服务器连接端口
    port: 6379

    # Redis服务器连接密码（默认为空）
    password:

    pool:
      max-active: 200

      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

      # 连接池中的最大空闲连接
      max-idle: 10

      # 连接池中的最小空闲连接
      pool.min-idle: 0

      # 连接超时时间（毫秒）
      timeout: 1000

  datasource:
    druid:
      url: jdbc:mysql://192.168.137.241:3306/sso?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: fanghb
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: com.fhb.sso.core.domain
  mapper-locations: classpath:mapper/*.xml


